// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
				static class Vsix
				{
								public const string Id = "68ACD1E1-1F94-4820-94CD-D78A9B7C4B37";
								public const string Name = "Add New Migration";
								public const string Description = @"The fastest and easiest way to add new migration files to any project - including files that start with a dot";
								public const string Language = "en-US";
								public const string Version = "1.0";
								public const string Author = "Daniel Murta";
								public const string Tags = "migration, file, add, template";
				}
}
